version: '3.8'

services:
  db_postgres:
    image: postgres:14
    container_name: db_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd.1
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres


volumes:
  postgres_data: